version: '3.8'

services:
  frontend:
    # 必須改成你推送到 Docker Hub 的 Image 名稱
    image: bananaice/auror_frontend:latest 
    container_name: auror_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80" # 這是 Azure 唯一會看見並導流的對外 Port
    # 注意：這裡的 volumes 掛載全拿掉了，檔案必須直接打包進 Image 裡

  backend:
    # 同樣必須使用預先打包好的 Image
    image: bananaice/auror_backend:latest
    container_name: auror_backend
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: auror_vapor
    # 後端不開放 Port，讓前端 (Caddy) 透過內部網路去反向代理它

  db:
    # 如果有初始化腳本，資料庫也需要打包成自己的 Image
    image: bananaice/auror_db:latest
    restart: always
    shm_size: 128mb
    container_name: auror_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auror_vapor
    # 不開放 5432 對外，僅限 backend 存取
    # volumes:
    #  - db_data:/var/lib/postgresql/data # 在 Azure App Service 常常會因為儲存體權限問題導致 db 崩潰，改為暫時性儲存以利於部署

# 宣告具名 volume
# volumes:
#   db_data: